<?php

use Illuminate\Database\Seeder;

class AgenciesTableSeeder extends Seeder
{
    private $agencies = [
        // Organisasi Perangkat Daerah
        ['id' => '1.1.01', 'name' => 'Biro Pemerintahan dan Otonomi Daerah', 'agency_type_id' => 1],
        ['id' => '1.1.02', 'name' => 'Biro Kesejahteraan Rakyat', 'agency_type_id' => 1],
        ['id' => '1.1.03', 'name' => 'Biro Hukum dan Hak Asasi Manusia', 'agency_type_id' => 1],
        ['id' => '1.2.01', 'name' => 'Biro Perekonomian', 'agency_type_id' => 1],
        ['id' => '1.2.02', 'name' => 'Biro Administrasi Pembangunan', 'agency_type_id' => 1],
        ['id' => '1.2.03', 'name' => 'Biro Administrasi Pengadaan Barang/Jasa', 'agency_type_id' => 1],
        ['id' => '1.3.01', 'name' => 'Biro Organisasi', 'agency_type_id' => 1],
        ['id' => '1.3.02', 'name' => 'Biro Umum', 'agency_type_id' => 1],
        ['id' => '1.3.03', 'name' => 'Biro Humas dan Protokol', 'agency_type_id' => 1],
        ['id' => '2', 'name' => 'Sekretariat Dewan Perwakilan Rakyat Daerah', 'agency_type_id' => 1],
        ['id' => '3', 'name' => 'Inspektorat', 'agency_type_id' => 1],
        ['id' => '4.01', 'name' => 'Dinas Pendidikan', 'agency_type_id' => 1],
        ['id' => '4.02', 'name' => 'Dinas Kepemudaan dan Olahraga', 'agency_type_id' => 1],
        ['id' => '4.03', 'name' => 'Dinas Kesehatan', 'agency_type_id' => 1],
        ['id' => '4.04', 'name' => 'Dinas Sosial', 'agency_type_id' => 1],
        ['id' => '4.05', 'name' => 'Dinas Pemberdayaan Masyarakat dan Desa', 'agency_type_id' => 1],
        ['id' => '4.06', 'name' => 'Dinas Komunikasi, Informatika, dan Statistik', 'agency_type_id' => 1],
        ['id' => '4.07', 'name' => 'Dinas Ketahanan Pangan', 'agency_type_id' => 1],
        ['id' => '4.08', 'name' => 'Dinas Perhubungan', 'agency_type_id' => 1],
        ['id' => '4.09', 'name' => 'Dinas Koperasi, Usaha Kecil dan Menengah', 'agency_type_id' => 1], 
        ['id' => '4.10', 'name' => 'Dinas Kebudayaan', 'agency_type_id' => 1],
        ['id' => '4.11', 'name' => 'Dinas Kearsipan dan Perpustakaan', 'agency_type_id' => 1],
        ['id' => '4.12', 'name' => 'Dinas Perdagangan dan Perindustrian', 'agency_type_id' => 1],
        ['id' => '4.13', 'name' => 'Dinas Pariwisata', 'agency_type_id' => 1],
        ['id' => '4.14', 'name' => 'Dinas Tenaga Kerja dan Energi Sumber Daya Mineral', 'agency_type_id' => 1],
        ['id' => '4.15', 'name' => 'Satuan Polisi Pamong Praja', 'agency_type_id' => 1],
        ['id' => '4.16', 'name' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'agency_type_id' => 1],
        ['id' => '4.17', 'name' => 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak', 'agency_type_id' => 1],
        ['id' => '4.18', 'name' => 'Dinas Lingkungan Hidup', 'agency_type_id' => 1],
        ['id' => '4.19', 'name' => 'Dinas Kependudukan, Pencatatan Sipil dan Keluarga Berencana', 'agency_type_id' => 1],
        ['id' => '4.20', 'name' => 'Dinas Kelautan dan Perikanan', 'agency_type_id' => 1],
        ['id' => '4.21', 'name' => 'Dinas Pekerjaan Umum dan Penataan Ruang', 'agency_type_id' => 1],
        ['id' => '4.22', 'name' => 'Dinas Tanaman Pangan, Hortikultura dan Perkebunan', 'agency_type_id' => 1],
        ['id' => '4.23', 'name' => 'Dinas Peternakan dan Kesehatan Hewan', 'agency_type_id' => 1],
        ['id' => '4.24', 'name' => 'Dinas Perumahan Rakyat dan Kawasan Permukiman', 'agency_type_id' => 1],
        ['id' => '4.25', 'name' => 'Dinas Kehutanan', 'agency_type_id' => 1],
        ['id' => '5.01', 'name' => 'Badan Perencanaan Pembangunan Daerah, Penelitian dan Pengembangan', 'agency_type_id' => 1],
        ['id' => '5.02', 'name' => 'Badan Kepegawaian Daerah', 'agency_type_id' => 1],
        ['id' => '5.03', 'name' => 'Badan Pengembangan Sumber Daya Manusia', 'agency_type_id' => 1],
        ['id' => '5.04', 'name' => 'Badan Pengelola Keuangan dan Aset Daerah', 'agency_type_id' => 1],
        ['id' => '5.05', 'name' => 'Badan Pendapatan Daerah', 'agency_type_id' => 1],
        ['id' => '5.06', 'name' => 'Badan Penanggulana Bencana Daerah', 'agency_type_id' => 1],
        ['id' => '5.07', 'name' => 'Badan Penghubung', 'agency_type_id' => 1],
        ['id' => '5.08', 'name' => 'Badan Kesatuan Bangsa dan Politik', 'agency_type_id' => 1],

        // Sekolah
        ['id' => '50103121', 'name' => 'SMAN 6 Denpasar', 'agency_type_id' => 2],        
        ['id' => '50103122', 'name' => 'SMAN 5 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103126', 'name' => 'SMAN 2 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103125', 'name' => 'SMAN 3 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103124', 'name' => 'SMAN 4 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103127', 'name' => 'SMAN 1 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103120', 'name' => 'SMAN 7 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103632', 'name' => 'SMAN 8 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103118', 'name' => 'SMKN 1 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103115', 'name' => 'SMKN 4 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103638', 'name' => 'SMKN 5 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103117', 'name' => 'SMKN 2 Denpasar', 'agency_type_id' => 2],
        ['id' => '50103116', 'name' => 'SMKN 3 Denpasar', 'agency_type_id' => 2],

        ['id' => '50100845', 'name' => 'SMAN 1 Melaya', 'agency_type_id' => 2],
        ['id' => '50100844', 'name' => 'SMAN 1 Mendoyo', 'agency_type_id' => 2],
        ['id' => '50105469', 'name' => 'SMAN 2 Mendoyo', 'agency_type_id' => 2],
        ['id' => '50100842', 'name' => 'SMAN 2 Pekutatan', 'agency_type_id' => 2],
        ['id' => '50100843', 'name' => 'SMAN 1 Negara', 'agency_type_id' => 2],
        ['id' => '50100824', 'name' => 'SMAN 2 Negara', 'agency_type_id' => 2],
        ['id' => '50103897', 'name' => 'SMKN 3 Negara', 'agency_type_id' => 2],
        ['id' => '69763291', 'name' => 'SMKN 5 Negara', 'agency_type_id' => 2],
        ['id' => '50100802', 'name' => 'SMKN 2 Negara', 'agency_type_id' => 2],
        ['id' => '50100803', 'name' => 'SMKN 1 Negara', 'agency_type_id' => 2],
        ['id' => '60724579', 'name' => 'SMKN 4 Negara', 'agency_type_id' => 2],

        ['id' => '50101122', 'name' => 'SMAN 1 Selemadeg', 'agency_type_id' => 2],
        ['id' => '50101125', 'name' => 'SMAN 1 Kerambitan', 'agency_type_id' => 2],
        ['id' => '50101124', 'name' => 'SMAN 1 Kediri', 'agency_type_id' => 2],
        ['id' => '50101121', 'name' => 'SMAN 1 Tabanan', 'agency_type_id' => 2],
        ['id' => '50101101', 'name' => 'SMAN 2 Tabanan', 'agency_type_id' => 2],
        ['id' => '50101132', 'name' => 'SMAN 1 Marga', 'agency_type_id' => 2],
        ['id' => '50101131', 'name' => 'SMAN 1 Baturiti', 'agency_type_id' => 2],
        ['id' => '50101126', 'name' => 'SMAN 1 Penebel', 'agency_type_id' => 2],
        ['id' => '50101133', 'name' => 'SMAN 1 Pupuan', 'agency_type_id' => 2],
        ['id' => '50103438', 'name' => 'SMKN 3 Tabanan', 'agency_type_id' => 2],
        ['id' => '50101103', 'name' => 'SMKN 1 Tabanan', 'agency_type_id' => 2],
        ['id' => '50101104', 'name' => 'SMKN 2 Tabanan', 'agency_type_id' => 2],

        ['id' => '50101706', 'name' => 'SMAN 1 Kuta Selatan', 'agency_type_id' => 2],
        ['id' => '50101705', 'name' => 'SMAN 1 Kuta', 'agency_type_id' => 2],
        ['id' => '50101694', 'name' => 'SMAN 2 Kuta', 'agency_type_id' => 2],
        ['id' => '50101696', 'name' => 'SMAN 1 Kuta Utara', 'agency_type_id' => 2],
        ['id' => '50101695', 'name' => 'SMAN 1 Mengwi', 'agency_type_id' => 2],
        ['id' => '50101684', 'name' => 'SMAN 2 Mengwi', 'agency_type_id' => 2],
        ['id' => '50101704', 'name' => 'SMAN 1 Abiansemal', 'agency_type_id' => 2],
        ['id' => '50103610', 'name' => 'SMAN 1 Petang', 'agency_type_id' => 2],
        ['id' => '50101623', 'name' => 'SMKN 1 Petang', 'agency_type_id' => 2],
        ['id' => '50101688', 'name' => 'SMKN 1 Kuta Selatan', 'agency_type_id' => 2],

        ['id' => '50102081', 'name' => 'SMAN 1 Sukawati', 'agency_type_id' => 2],
        ['id' => '50102078', 'name' => 'SMAN 1 Blahbatuh', 'agency_type_id' => 2],
        ['id' => '50102079', 'name' => 'SMAN 1 Gianyar', 'agency_type_id' => 2],
        ['id' => '50102082', 'name' => 'SMAN 1 Tampaksiring', 'agency_type_id' => 2],
        ['id' => '50102004', 'name' => 'SMAN 1 Ubud', 'agency_type_id' => 2],
        ['id' => '50102094', 'name' => 'SMAN 1 Tegallalang', 'agency_type_id' => 2],
        ['id' => '50102080', 'name' => 'SMAN 1 Payangan', 'agency_type_id' => 2],
        ['id' => '69929909', 'name' => 'SMKN 2 Tegallalang', 'agency_type_id' => 2],
        ['id' => '50103614', 'name' => 'SMKN 1 Tegallalang', 'agency_type_id' => 2],
        ['id' => '50103388', 'name' => 'SMKN 1 Mas Ubud', 'agency_type_id' => 2],
        ['id' => '50103356', 'name' => 'SMKN 1 Tampaksiring', 'agency_type_id' => 2],
        ['id' => '50102018', 'name' => 'SMKN 1 Gianyar', 'agency_type_id' => 2],
        ['id' => '50102019', 'name' => 'SMKN 1 Sukawati', 'agency_type_id' => 2],
        ['id' => '50102020', 'name' => 'SMKN 2 Sukawati', 'agency_type_id' => 2],
        ['id' => '50102021', 'name' => 'SMKN 3 Sukawati', 'agency_type_id' => 2],

        ['id' => '50102378', 'name' => 'SMAN 1 Nusa Penida', 'agency_type_id' => 2],
        ['id' => '50105536', 'name' => 'SMAN Satu Atap Klumpu', 'agency_type_id' => 2],
        ['id' => '69873946', 'name' => 'SMAN Satu Atap Lembongan', 'agency_type_id' => 2],
        ['id' => '50104096', 'name' => 'SMAN Satu Atap Nusa Penida', 'agency_type_id' => 2],
        ['id' => '50102379', 'name' => 'SMAN 1 Banjarangkan', 'agency_type_id' => 2],
        ['id' => '50102366', 'name' => 'SMAN 1 Semarapura', 'agency_type_id' => 2],
        ['id' => '50102365', 'name' => 'SMAN 2 Semarapura', 'agency_type_id' => 2],
        ['id' => '50103365', 'name' => 'SMAN 1 Dawan', 'agency_type_id' => 2],
        ['id' => '50102353', 'name' => 'SMKN 1 Klungkung', 'agency_type_id' => 2],
        ['id' => '50103366', 'name' => 'SMKN 1 Nusa Penida', 'agency_type_id' => 2],

        ['id' => '50102577', 'name' => 'SMAN 1 Susut', 'agency_type_id' => 2],
        ['id' => '50102568', 'name' => 'SMAN 1 Bangli', 'agency_type_id' => 2],
        ['id' => '50102575', 'name' => 'SMAN 2 Bangli', 'agency_type_id' => 2],
        ['id' => '50102576', 'name' => 'SMAN 1 Tembuku', 'agency_type_id' => 2],
        ['id' => '50102578', 'name' => 'SMAN 1 Kintamani', 'agency_type_id' => 2],
        ['id' => '50102574', 'name' => 'SMKN 1 Kintamani', 'agency_type_id' => 2],
        ['id' => '50102571', 'name' => 'SMKN 2 Kintamani', 'agency_type_id' => 2],
        ['id' => '50105403', 'name' => 'SMKN 3 Kintamani', 'agency_type_id' => 2],
        ['id' => '50105524', 'name' => 'SMKN 1 Tembuku', 'agency_type_id' => 2],
        ['id' => '50102553', 'name' => 'SMKN 1 Bangli', 'agency_type_id' => 2],
        ['id' => '50102572', 'name' => 'SMKN 2 Bangli', 'agency_type_id' => 2],
        ['id' => '50102569', 'name' => 'SMKN 3 Bangli', 'agency_type_id' => 2],
        ['id' => '50102570', 'name' => 'SMKN 4 Bangli', 'agency_type_id' => 2],
        ['id' => '50102573', 'name' => 'SMKN 1 Susut', 'agency_type_id' => 2],

        ['id' => '50103671', 'name' => 'SMAN 1 Rendang', 'agency_type_id' => 2],
        ['id' => '50102780', 'name' => 'SMAN 1 Sidemen', 'agency_type_id' => 2],
        ['id' => '50103670', 'name' => 'SMAN 1 Manggis', 'agency_type_id' => 2],
        ['id' => '50102790', 'name' => 'SMAN 1 Amplapura', 'agency_type_id' => 2],
        ['id' => '50102779', 'name' => 'SMAN 2 Amplapura', 'agency_type_id' => 2],
        ['id' => '50103361', 'name' => 'SMAN 3 Amplapura', 'agency_type_id' => 2],
        ['id' => '50103745', 'name' => 'SMAN 1 Bebandem', 'agency_type_id' => 2],
        ['id' => '50102781', 'name' => 'SMAN 1 Selat', 'agency_type_id' => 2],
        ['id' => '50103669', 'name' => 'SMAN 1 Kubu', 'agency_type_id' => 2],
        ['id' => '50103852', 'name' => 'SMKN 1 Kubu', 'agency_type_id' => 2],
        ['id' => '69902191', 'name' => 'SMKN 1 Bebandem', 'agency_type_id' => 2],
        ['id' => '50102771', 'name' => 'SMKN 1 Abang', 'agency_type_id' => 2],
        ['id' => '69762794', 'name' => 'SMKN 1 Amlapura', 'agency_type_id' => 2],
        ['id' => '50103677', 'name' => 'SMKN 1 Manggis', 'agency_type_id' => 2],

        ['id' => '50100390', 'name' => 'SMAN 1 Gerokgak', 'agency_type_id' => 2],
        ['id' => '50103723', 'name' => 'SMAN 2 Gerokgak', 'agency_type_id' => 2],
        ['id' => '50100412', 'name' => 'SMAN 1 Seririt', 'agency_type_id' => 2],
        ['id' => '50100386', 'name' => 'SMAN 1 Busungbiu', 'agency_type_id' => 2],
        ['id' => '50100284', 'name' => 'SMAN 2 Busungbiu', 'agency_type_id' => 2],
        ['id' => '50100388', 'name' => 'SMAN 1 Banjar', 'agency_type_id' => 2],
        ['id' => '50100283', 'name' => 'SMAN 2 Banjar', 'agency_type_id' => 2],
        ['id' => '50100262', 'name' => 'SMAN 1 Sukasada', 'agency_type_id' => 2],
        ['id' => '50100337', 'name' => 'SMAN 1 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100285', 'name' => 'SMAN 2 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100286', 'name' => 'SMAN 3 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100287', 'name' => 'SMAN 4 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100392', 'name' => 'SMAN 1 Sawan', 'agency_type_id' => 2],
        ['id' => '50100391', 'name' => 'SMAN 1 Kubutambahan', 'agency_type_id' => 2],
        ['id' => '50105492', 'name' => 'SMAN Bali Mandara', 'agency_type_id' => 2],
        ['id' => '50100282', 'name' => 'SMAN 1 Tejakula', 'agency_type_id' => 2],
        ['id' => '50103724', 'name' => 'SMAN 2 Tejakula', 'agency_type_id' => 2],
        ['id' => '69760689', 'name' => 'SMAN Satu Atap Tejakula', 'agency_type_id' => 2],
        ['id' => '50104216', 'name' => 'SMKN 1 Tejakula', 'agency_type_id' => 2],
        ['id' => '69899478', 'name' => 'SMKN Bali Mandara', 'agency_type_id' => 2],
        ['id' => '50105414', 'name' => 'SMKN 1 Kubutambahan', 'agency_type_id' => 2],
        ['id' => '50105503', 'name' => 'SMKN 1 Sawan', 'agency_type_id' => 2],
        ['id' => '50100288', 'name' => 'SMKN 1 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100290', 'name' => 'SMKN 2 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100291', 'name' => 'SMKN 3 Singaraja', 'agency_type_id' => 2],
        ['id' => '50100289', 'name' => 'SMKN 1 Sukasada', 'agency_type_id' => 2],
        ['id' => '69847710', 'name' => 'SMKN 1 Busungbiu', 'agency_type_id' => 2],
        ['id' => '50103727', 'name' => 'SMKN 1 Seririt', 'agency_type_id' => 2],
        ['id' => '50103728', 'name' => 'SMKN 2 Seririt', 'agency_type_id' => 2],
        ['id' => '69899614', 'name' => 'SMKN 1 Gerokgak', 'agency_type_id' => 2],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->agencies as $agency) {
            App\Agency::create($agency);
        }
    }
}